application: digit-sudoku
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /app
  static_dir: app

- url: /node_modules
  static_dir: node_modules

- url: /
  static_files: digit.html
  upload: digit.html

- url: /.*
  static_files: 404.html
  upload: 404.html

skip_files:
- ^node_modules/gulp(.*/)?(.*/)?.*$
- ^node_modules/jade/(.*/)?.*$
